---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          RELEASE_VERSION="$(echo "$RELEASE_VERSION" | tr -d 'v')"
          sed -i "s/^\(VERSION\)=.*/\1=$RELEASE_VERSION/" hyprsnap

      - name: Check version
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          if ! VERSION="$(./hyprsnap --version)"; then
              echo "ERROR: failed to get version."
              exit 1
          fi
          if [ "v$VERSION" != "$RELEASE_VERSION" ]; then
              echo "ERROR: version mismatch: 'v$VERSION' != '$RELEASE_VERSION'"
              exit 1
          fi

      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          files: hyprsnap
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Update PKGBUILD
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          RELEASE_VERSION="$(echo "$RELEASE_VERSION" | tr -d 'v')"
          sed -i "s/PLACEHOLDER_VERSION/$RELEASE_VERSION/g" aur/PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: hyprsnap
          pkgbuild: ./aur/PKGBUILD
          updpkgsums: true
          test: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
